version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  migrate:
    image: migrate/migrate
    container_name: migrate
    command: -path=sql/migrations -database "mysql://root:root@tcp(mysql:3306)/orders" up
    volumes:
      - ./sql/migrations:/sql/migrations
    depends_on:
      - mysql
  
  app:
    build: .
    image: manueldembo/ordersystem:latest
    container_name: app
    restart: always
    command: >
      dockerize
      -wait tcp://mysql:3306
      -wait tcp://rabbitmq:5672
      -timeout 30s
      ./ordersystem
    ports:
      - 8000:8000
      - 50051:50051
      - 8080:8080
    depends_on:
      - mysql
      - rabbitmq
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/mydb
      RABBITMQ_URL: amqp://rabbitmq:5672